# Generated by Django 3.0.8 on 2020-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('address_id', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('max_capacity', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('resource_id', models.IntegerField()),
            ],
            options={
                'db_table': 'queue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('resource_id', models.IntegerField()),
                ('train_from', models.CharField(max_length=30)),
                ('train_to', models.CharField(max_length=30)),
                ('max_occupancy', models.IntegerField()),
                ('occupancy_sensor', models.CharField(max_length=20)),
                ('updated_date', models.DateField()),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
    ]
