# Generated by Django 3.0.8 on 2020-07-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='queue_id',
            new_name='person_id',
        ),
    ]
