# Generated by Django 3.0.3 on 2020-07-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('address_id', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('resource_id', models.IntegerField()),
                ('train_from', models.CharField(max_length=30)),
                ('train_to', models.CharField(max_length=30)),
                ('max_occupancy', models.IntegerField()),
                ('occupancy_sensor', models.CharField(max_length=20)),
                ('updated_date', models.DateField()),
            ],
            options={
                'db_table': 'resource',
                'unique_together': {('resource_id', 'train_from', 'train_to', 'updated_date')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('max_capacity', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('resource_id', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='smartqueueapi.Location')),
            ],
            options={
                'db_table': 'queue',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='smartqueueapi.Resource'),
        ),
    ]
